ALTER TABLE ingredients
    ADD COLUMN IF NOT EXISTS calories DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS protein DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS fat DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS carbs DOUBLE PRECISION NOT NULL DEFAULT 0;

